### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by konstantinstadler** [NTNU-IndEcol/db_project_indecol#2]
Not urgent, but we should find a cool name instead of db-project-indecol. put ideas below

**Comment by konstantinstadler** [comment]
Mneme - after the muse of memory

**Comment by CandyDeck** [comment]
I've been looking at acronym generator :

**INERTIA** | **IN**d**E**col p**R**ojec**T** h**I**story d**A**tabase

**Comment by konstantinstadler** [comment]
Decided on IndEcx
