### ISSUE TITLE
Multichoice -> keyword, method, group, ...

### ISSUE THREAD

**Issue by CandyDeck** [NTNU-IndEcol/db_project_indecol#3]
@hazimhussein 

in models.py, project is defined for now as :
```

class Project(models.Model):

    project_id = models.CharField(
        unique=True,
        null=False,
        blank=False,
        max_length=50
    )


    name= models.CharField(
        null=False,
        blank=False,
        max_length=50
    )

    description = models.TextField(
        null = False,
        blank= False,
        max_length=2000
    )

    start_date= models.DateField(
        null = False,
        blank=False
    )

    end_date= models.DateField(
        null = True,
        blank= True
    )

    keywords_id = models.CharField(
        choices=keyword_choices,
        max_length=14,
        default='Choose'
    )

    methods = models.CharField(
        choices = method_choices,
        max_length=6,
        default='Choose'
    )

    type = models.CharField(
        choices = project_choices,
        max_length= 3,
        default='Choose'

    )


```
following discussion, can you please check this out ? Multiple choice does not seems to be an option here.

**Comment by hazimhussein** [comment]
I have attached a branch to the issue with edits that should fix this for the keywords field. 
Basically, I made the keywords field a regular charfield and then edited the admin form to show it as a multiselect option and save it as a string combining the options eg: "option1, option2, option3, ..."

We will probably need to edit the admin forms a lot in the future, so it may be also worth it to take a look at [Django Admin Forms](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.form)

**Comment by CandyDeck** [comment]
> I have attached a branch to the issue with edits that should fix this for the keywords field. Basically, I made the keywords field a regular charfield and then edited the admin form to show it as a multiselect option and save it as a string combining the options eg: "option1, option2, option3, ..."
> 
> We will probably need to edit the admin forms a lot in the future, so it may be also worth it to take a look at [Django Admin Forms](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.form)

This looks great thanks ! I made a pull request and I am now working on implementing something similar for the methods.

**Comment by CandyDeck** [comment]
@hazimhussein , I attached to the issue a branch too ... This will allow the multichoice for methods
