### ISSUE TITLE
Please add a description to the FAQ for admin on how to delete an entry

### ISSUE THREAD

**Issue by konstantinstadler** [NTNU-IndEcol/db_project_indecol#36]
I already did the one for the normal users, but we need some guidance for us on how to do that.

**Comment by konstantinstadler** [comment]
@hazimhussein : is the delete symbol for everyone of just admin? there are now 2 contradicting explaination (2 help entries). For this it would also be good to have a test user with standard rights so admin can check the page for normal users

**Comment by hazimhussein** [comment]
@konstantinstadler the delete symbol is only for admin members, 
I can't find the contradicting entries in the help, could you point to which one are they so I can fix them.

**Comment by konstantinstadler** [comment]
Mmmh, can also not find it anymore, perhaps was just confused about the admin/non admin, the new test user makes that much clearer
