### ISSUE TITLE
Resources - description is wrong

### ISSUE THREAD

**Issue by konstantinstadler** [NTNU-IndEcol/db_project_indecol#37]
When hovering over the resources it currently says "resources the project used", but it rather "Project resources and outcomes" - the focus is more on output of projects

**Comment by hazimhussein** [comment]
I fixed this part.
The description and icons that represent the tables are actually part of the database which can be adjusted from the admin page
https://indecx.indecol.no/admin
I will add more detailed intructions about in the help section
