### ISSUE TITLE
URGENT: FAQ are only updating for the current user

### ISSUE THREAD

**Issue by konstantinstadler** [NTNU-IndEcol/db_project_indecol#39]
I put some more info into the FAQ section, but it only shows for me.
The new entries are not visible when I logout, and I had a short glimpse at Johans version and they also where not there.
Is there some update process in the background we need to initiate/takes some time?

**Comment by hazimhussein** [comment]
This should be fixed now,
The problem was that the non admin entries were hidden instead of the admin ones
